"""Константы проекта."""

MAX_LENGTH_STR = 30
MAX_LENGTH_SLUG = 50
MAX_LENGTH_NAME = 256

MAX_LENGTH_USERNAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150

USER = 'user'
MODERATOR = 'moderator'
ADMIN = 'admin'
ROLE_CHOICES = [
    (USER, 'Пользователь'),
    (MODERATOR, 'Модератор'),
    (ADMIN, 'Админ'),
]

MIN_VALUE_SCORE = 1
MAX_VALUE_SCORE = 10
